### ISSUE TITLE
Date/Time

### ISSUE THREAD

**Issue by bfcns** [h3llrais3r/deluge-myscheduler#12]
It will be useful if it would show the current time the scheduler is using...

**Comment by h3llrais3r** [comment]
Please share some more info because I don't really understand what you are asking...

**Comment by bfcns** [comment]
Sure... I am using deluge in a server setting (Linux) Sometimes the time of the server changes, or daylight savings time etc. I do not usually check the server date/time from the shell... So it would be nice if the add-on would show the current server time the myscheduler uses. I hope this is better...

**Comment by h3llrais3r** [comment]
Does your client has a different time than your server in that case? Because I'm also running deluge on a server (Windows) but my client has the same time as the server, so if you check the current time of your client, you know the time on your server, no?
Next to that, there is nothing visible of the myscheduler plugin when it's in use... just like the original scheduler plugin.

**Comment by bfcns** [comment]
Yes I am running a Windows Deluge thin Client: 2.0.4.dev37, Linux headless deluge Server: 2.0.3.

The time can be in status bar in main menu and it can also be optional. It can be implemented to other scheduler too... or maybe in the main app not in the plugin... but it is only useful if I enable scheduler.

Sorry for the confusion, thanks for understanding.

**Comment by h3llrais3r** [comment]
Stale issue.
