### ISSUE TITLE
Did not stop torrents

### ISSUE THREAD

**Issue by bfcns** [h3llrais3r/deluge-myscheduler#13]
The MyScheduler supposed to stop all torrents at 8am... but it did not until I had to open the plugin config and click Apply, then it worked.

**Comment by h3llrais3r** [comment]
Perhaps you didn't apply it the first time?
Please provide debug logs, so I can see what's going on. Also tell me which version you are using, because there are 2 versions available, 1 for deluge 1.3.x and 1 for deluge 2.x which is currently in alpha phase...

**Comment by bfcns** [comment]
I am running a Windows Deluge thin Client: 2.0.4.dev37, Linux headless deluge Server: 2.0.3.

I am using MyScheduler-2.0.0a1-py3.6.egg from https://github.com/h3llrais3r/deluge-myscheduler/releases/tag/2.0.0a1 but I think as py3.8.

I will try to check the logs if I can replicate the problem.

**Comment by bfcns** [comment]
Today I was able to check the same thing with the built-in plugin. The same thing happened.

But then realized it stopped around 1 minute later the scheduled time 8:01am.

Is this a large cache usage problem or something else?

**Comment by h3llrais3r** [comment]
@phpcitizen It probably takes some time to stop/pauze all your torrents so there might be some delay.
Since you said it stopped around 1 minute later, I don't consider this as a bug and I'll close it.
If you still feel it's a bug, I propose you open a ticket in the original scheduler, as this one is using the same code base. 😉
