### ISSUE TITLE
1.3.13 Force Start Broken

### ISSUE THREAD

**Issue by mastafrooper** [h3llrais3r/deluge-myscheduler#4]
As of updating the Deluge 1.3.13 the force start option seems to be broken. The scheduling part works correctly it would seem but when you tell a torrent to be forced it stays paused during the off schedule.

Have confirmed this on two separate Deluge install on two different machines.

Both are Windows 10 Pro x64 though.

**Comment by cas--** [comment]
Likely due to pausing session changes in deluge core so this plugin would need to pause every torrent individually (as it used to be in deluge core rather than whole session as it does now).

**Comment by h3llrais3r** [comment]
I was just looking at the changelog and I had the same impression. :smile: 
@cas-- I suppose you are referring to http://dev.deluge-torrent.org/changeset/73152558317d47d?
But when I look at my plugin, I was already using this version because I merged the code after your commit 10 months ago...
See https://github.com/h3llrais3r/deluge-myscheduler/blob/master/myscheduler/core.py#L155
See https://github.com/h3llrais3r/deluge-myscheduler/blob/master/myscheduler/core.py#L181
See https://github.com/h3llrais3r/deluge-myscheduler/blob/master/myscheduler/core.py#L184

I'll have a look when I have a bit more time (next month). 
Meanwhile, please use version 1.3.12 until the plugin is updated.

**Comment by cas--** [comment]
I did see that but I'm not sure how you can force a torrent to start if the entire session is paused? I changed the functionality of that method, in hindsight perhaps should not have done that to core methods and instead created a new method `pause_session` and leave `pause_all_torrents` as deprecated.

The solution would be to create two pause and resume methods in the plugin that has the old core functionality. Obviously this would then mean the plugin would have the #1330 bug again unless it keeps track of torrents status before pausing and resets them upon resuming.

**Comment by h3llrais3r** [comment]
@cas-- What do you advise? If I'm seeing your last comment, there is currently no way to force start a single torrent when the entire session is paused?
Except creating new pause and resume methods myself in my plugin, like you mentioned?

**Comment by h3llrais3r** [comment]
@mastafrooper Can you try with the egg in attachment? I made some changes based on the feedback of @cas--  and it seems to work for me with deluge 1.3.13.
Can you double check and let me know if it works? If yes, I'll create a new version of my plugin with the changes.
[MyScheduler-0.3.1-py2.7.zip](https://github.com/h3llrais3r/deluge-myscheduler/files/391285/MyScheduler-0.3.1-py2.7.zip)

**Comment by mastafrooper** [comment]
@h3llrais3r the 0.3.1 version you posted seems to be working perfectly at the moment.

Thanks for you hard work.

**Comment by h3llrais3r** [comment]
Thanks for your feedback. I'll commit the changes and make a release as soon as possible.

**Comment by h3llrais3r** [comment]
Fixed with 59ab6f373d4b687186d0a53e072f8f5f53010e3b and release https://github.com/h3llrais3r/deluge-myscheduler/releases/tag/0.3.1
